/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgnesKeysRouteImport } from './routes/api/agnes-keys'
import { Route as ApiPromptsRouteImport } from './routes/api/prompts'
import { Route as ApiProxyImageRouteImport } from './routes/api/proxy-image'
import { Route as ApiPublicAgnesProbeRouteImport } from './routes/api/public/agnes-probe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgnesKeysRoute = ApiAgnesKeysRouteImport.update({
  id: '/api/agnes-keys',
  path: '/api/agnes-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptsRoute = ApiPromptsRouteImport.update({
  id: '/api/prompts',
  path: '/api/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyImageRoute = ApiProxyImageRouteImport.update({
  id: '/api/proxy-image',
  path: '/api/proxy-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgnesProbeRoute = ApiPublicAgnesProbeRouteImport.update({
  id: '/api/public/agnes-probe',
  path: '/api/public/agnes-probe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agnes-keys': typeof ApiAgnesKeysRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/public/agnes-probe': typeof ApiPublicAgnesProbeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agnes-keys': typeof ApiAgnesKeysRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/public/agnes-probe': typeof ApiPublicAgnesProbeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agnes-keys': typeof ApiAgnesKeysRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/proxy-image': typeof ApiProxyImageRoute
  '/api/public/agnes-probe': typeof ApiPublicAgnesProbeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/agnes-keys'
    | '/api/prompts'
    | '/api/proxy-image'
    | '/api/public/agnes-probe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/agnes-keys'
    | '/api/prompts'
    | '/api/proxy-image'
    | '/api/public/agnes-probe'
  id:
    | '__root__'
    | '/'
    | '/api/agnes-keys'
    | '/api/prompts'
    | '/api/proxy-image'
    | '/api/public/agnes-probe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgnesKeysRoute: typeof ApiAgnesKeysRoute
  ApiPromptsRoute: typeof ApiPromptsRoute
  ApiProxyImageRoute: typeof ApiProxyImageRoute
  ApiPublicAgnesProbeRoute: typeof ApiPublicAgnesProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agnes-keys': {
      id: '/api/agnes-keys'
      path: '/api/agnes-keys'
      fullPath: '/api/agnes-keys'
      preLoaderRoute: typeof ApiAgnesKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompts': {
      id: '/api/prompts'
      path: '/api/prompts'
      fullPath: '/api/prompts'
      preLoaderRoute: typeof ApiPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy-image': {
      id: '/api/proxy-image'
      path: '/api/proxy-image'
      fullPath: '/api/proxy-image'
      preLoaderRoute: typeof ApiProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agnes-probe': {
      id: '/api/public/agnes-probe'
      path: '/api/public/agnes-probe'
      fullPath: '/api/public/agnes-probe'
      preLoaderRoute: typeof ApiPublicAgnesProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgnesKeysRoute: ApiAgnesKeysRoute,
  ApiPromptsRoute: ApiPromptsRoute,
  ApiProxyImageRoute: ApiProxyImageRoute,
  ApiPublicAgnesProbeRoute: ApiPublicAgnesProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
